### ISSUE TITLE
When using NavigationPage on Android the NFC scanner does not work

### ISSUE THREAD

**Issue by Rigo09** [acaliaro/XamarinDemoNfc#1]
Hi @acaliaro, I have encountered the following error while testing the project.

I added a page that works as a main menu with a button that navigates to the ReadPage.xaml page.

In App.xaml.cs I substituted the following:

` publicApp()
        {
            InitializeComponent();
            MainPage = new ReadPage();
        }`
by

` publicApp()
        {
            InitializeComponent();
             MainPage = new NavigationPage(new MainMenu());
        }`

When used in this way the scan does not work. It works only if the ReadPage is the root page, then everything is fine and the tag is scanned.

**Steps to reproduce**
1.-Create two pages.
2.-Create a button on the first page that pushes to the ReadPage page
3.-Try to scan the NFC tag

I await your response, you have no idea how your example has helped me. Thank you so much

**Comment by acaliaro** [comment]
Hi.

Are you using the xamarin app or maui app?
Have you tried to add a breakpoint to MainActivity inside the OnNewIntent method? Do you receive the tag value?

**Comment by Rigo09** [comment]
Hi @acaliaro , I'm using the xamarin app. I haven't tried adding a breakpoint in the main activity yet.
I'm going to do that test.

**Comment by Rigo09** [comment]
Indeed the method is working fine. It is at another point where something is happening
![image](https://github.com/acaliaro/XamarinDemoNfc/assets/37517852/6bb8eb2e-516d-4840-9885-d74ecb2af66c)

**Comment by acaliaro** [comment]
You have to register the messages in page OnAppearing method. Take a look to read viemodel

**Comment by Rigo09** [comment]
Hi @acaliaro, I already found the way to solve it. What I did was that in the button that opens the page ReadPage.xaml I changed:
` private async void OnOpcion1ClickedAsync(object sender, EventArgs e)
        {
     
            await Navigation.PushAsync(new ReadPage());
        }`
by
` private async void OnOpcion1ClickedAsync(object sender, EventArgs e)
        {
     
            await Navigation.PushModalAsync(new ReadPage());
        }`

thank you very much for your help.
